# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
a = np.random.random((2,3,5))
a

array([[[0.75776751, 0.29447034, 0.5176093 , 0.94234779, 0.70343545],
        [0.06199679, 0.66414607, 0.9741012 , 0.62210248, 0.64279751],
        [0.06766557, 0.59258317, 0.52998326, 0.96252695, 0.51693544]],

       [[0.69518674, 0.46524849, 0.97152896, 0.89469892, 0.72097317],
        [0.06745306, 0.27197333, 0.35885652, 0.5588114 , 0.48132518],
        [0.91558802, 0.75963628, 0.97434228, 0.49777704, 0.4129498 ]]])

In [7]:
a = np.random.rand(2,3,5)
a

array([[[0.22131861, 0.67913047, 0.05880839, 0.97714413, 0.09695589],
        [0.22581897, 0.38891428, 0.88410562, 0.60013096, 0.68890101],
        [0.60232168, 0.21263816, 0.56224734, 0.88003292, 0.77056202]],

       [[0.32965298, 0.64280804, 0.75489   , 0.89724396, 0.94192406],
        [0.36146615, 0.19107918, 0.07322479, 0.85995981, 0.68964339],
        [0.99136376, 0.58640527, 0.92220403, 0.39201649, 0.68053744]]])

In [8]:
# Method 3

#### 4. Print *a*.


In [9]:
print(a[0:2])

[[[0.22131861 0.67913047 0.05880839 0.97714413 0.09695589]
  [0.22581897 0.38891428 0.88410562 0.60013096 0.68890101]
  [0.60232168 0.21263816 0.56224734 0.88003292 0.77056202]]

 [[0.32965298 0.64280804 0.75489    0.89724396 0.94192406]
  [0.36146615 0.19107918 0.07322479 0.85995981 0.68964339]
  [0.99136376 0.58640527 0.92220403 0.39201649 0.68053744]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
b = np.full((5,2,3),1)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [11]:
print (b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
add = a+b
add

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
c =b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
d = a+c
d
# it works because it is the same matrix  

array([[[1.22131861, 1.67913047, 1.05880839, 1.97714413, 1.09695589],
        [1.22581897, 1.38891428, 1.88410562, 1.60013096, 1.68890101],
        [1.60232168, 1.21263816, 1.56224734, 1.88003292, 1.77056202]],

       [[1.32965298, 1.64280804, 1.75489   , 1.89724396, 1.94192406],
        [1.36146615, 1.19107918, 1.07322479, 1.85995981, 1.68964339],
        [1.99136376, 1.58640527, 1.92220403, 1.39201649, 1.68053744]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
print (a)
print(d)
# the two arrays only have a gap of 1 since array c (and b) values is equal to 1 

[[[0.22131861 0.67913047 0.05880839 0.97714413 0.09695589]
  [0.22581897 0.38891428 0.88410562 0.60013096 0.68890101]
  [0.60232168 0.21263816 0.56224734 0.88003292 0.77056202]]

 [[0.32965298 0.64280804 0.75489    0.89724396 0.94192406]
  [0.36146615 0.19107918 0.07322479 0.85995981 0.68964339]
  [0.99136376 0.58640527 0.92220403 0.39201649 0.68053744]]]
[[[1.22131861 1.67913047 1.05880839 1.97714413 1.09695589]
  [1.22581897 1.38891428 1.88410562 1.60013096 1.68890101]
  [1.60232168 1.21263816 1.56224734 1.88003292 1.77056202]]

 [[1.32965298 1.64280804 1.75489    1.89724396 1.94192406]
  [1.36146615 1.19107918 1.07322479 1.85995981 1.68964339]
  [1.99136376 1.58640527 1.92220403 1.39201649 1.68053744]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
e= np.multiply(a,c)
e

array([[[0.22131861, 0.67913047, 0.05880839, 0.97714413, 0.09695589],
        [0.22581897, 0.38891428, 0.88410562, 0.60013096, 0.68890101],
        [0.60232168, 0.21263816, 0.56224734, 0.88003292, 0.77056202]],

       [[0.32965298, 0.64280804, 0.75489   , 0.89724396, 0.94192406],
        [0.36146615, 0.19107918, 0.07322479, 0.85995981, 0.68964339],
        [0.99136376, 0.58640527, 0.92220403, 0.39201649, 0.68053744]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
d_max = np.amax(d)
print("max: ", d_max)
d_min = np.amin(d)
print("min: ", d_min)
d_mean = np.mean(d)
print("mean: ", d_mean)

max:  1.9913637584890913
min:  1.0588083949469695
mean:  1.5721149936335184


# 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [24]:
f = np.empty([2,3,5])
print(f)

[[[0.22131861 0.67913047 0.05880839 0.97714413 0.09695589]
  [0.22581897 0.38891428 0.88410562 0.60013096 0.68890101]
  [0.60232168 0.21263816 0.56224734 0.88003292 0.77056202]]

 [[0.32965298 0.64280804 0.75489    0.89724396 0.94192406]
  [0.36146615 0.19107918 0.07322479 0.85995981 0.68964339]
  [0.99136376 0.58640527 0.92220403 0.39201649 0.68053744]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [25]:
f = []

for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
    if d_mean < x < d_max:
        f += [75]
    if x == d_mean:
        f += [50]
    if x == d_min:
        f += [0]
    if x == d_max:
        f += [100]
    
        
f = np.reshape(f, d.shape) 
print(f) 


[[[ 25  75   0  75  25]
  [ 25  25  75  75  75]
  [ 75  25  25  75  75]]

 [[ 25  75  75  75  75]
  [ 25  25  25  75  75]
  [100  75  75  25  75]]]


In [28]:
for l1 in range(0,2):
    for l2 in range(0,3):
        for el in range(0,5):
            if d_min<el<d_mean:
                f=25
            elif d_mean<el<d_max:
                f=75
            elif el==d_mean:
                f=50
            elif el==d_min:
                f=0
            elif el==d_max:
                f=100
print(f)

[[[ 25  75   0  75  25]
  [ 25  25  75  75  75]
  [ 75  25  25  75  75]]

 [[ 25  75  75  75  75]
  [ 25  25  25  75  75]
  [100  75  75  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [32]:
f = []

for x in np.nditer(d):
    if d_min < x < d_mean:
        f += ["B"]
    if d_mean < x < d_max:
        f += ["D"]
    if x == d_mean:
        f += ["C"]
    if x == d_min:
        f += ["A"]
    if x == d_max:
        f += ["E"]
    
        
f = np.reshape(f, d.shape) 
print(f) 


[[['B' 'D' 'A' 'D' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'B' 'D' 'D']]

 [['B' 'D' 'D' 'D' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['E' 'D' 'D' 'B' 'D']]]
